version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      python: 3.6
    #commands:
    #- echo Installing Dokcer ...
    #- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
    #- timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Loging into ECR ...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo Starting testing ...
      - python app/tests.py -f
      - echo Tests passed!
  build:
    commands:
      - echo Building ...
      - docker-compose build
      - echo Build completed
  post_build:
    commands:
      - echo Pushing to ECR ...
      - docker-compose push
      - echo Done with with Build Phase
