version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Loging into ECR ...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building ...
      - docker-compose build
      - echo Build completed
  post_build:
    commands:
      - echo Pushing to ECR ...
      - docker-compose push
      - echo Done with with Build Phase
