version: "3.7"

services:
    app:
        build:
            context: ./app
            args:
                - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        image: 980070691560.dkr.ecr.us-east-1.amazonaws.com/rx_tracker_app:latest
        expose:
            - "8000"

    nginx:
        build: ./nginx
        image: 980070691560.dkr.ecr.us-east-1.amazonaws.com/rx_tracker_nginx:latest
        ports:
            - "8080:8080"
        depends_on:
            - app
