version: '3.7'

services:
    web:
        build: ./app
        image: rxtracker:latest
        expose: 
            - "8000"
            
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - web 